language: cpp

branches:
  only:
    - master

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ibqt4-dev libqt4-private-dev libevent-dev

script:
  - cd src
  - qmake
  - make
  - cd ../tests-qt4
  - qmake
  - make
  - for i in ./tst_*; do ./$i; done
